"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pychat.py']
DATA_FILES = ['--iconfile']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/loan/Documents/Development/PyChat/graphics/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
